name = "gist-mom"
main = "src/server/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "GistRoom"
class_name = "GistRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GistRoom"]

[[d1_databases]]
binding = "DATABASE"
database_name = "gist-mom-auth"
database_id = "5188c070-8484-429e-bf99-ca1b32c9a404"

[vars]
GITHUB_CLIENT_ID = "Ov23lilf4Aq9AlPahXJW"

[dev]
ip = "127.0.0.1"
port = 1999
