name = "gist-mom"
main = "src/server/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "dist", binding = "ASSETS" }

[[durable_objects.bindings]]
name = "GistRoom"
class_name = "GistRoom"

[[migrations]]
tag = "v1"
new_classes = ["GistRoom"]

[[d1_databases]]
binding = "DATABASE"
database_name = "gist-mom-auth"
database_id = "local"

[vars]
GITHUB_CLIENT_ID = "Ov23liWqVF5OFktFycCL"

[build]
watch_dir = "src/server"

[dev]
ip = "127.0.0.1"
port = 1999
